-- Create table
create table T_AUTH_COMPONENT_PERMS
(
  perm_id          NUMBER generated by default as identity (nocache),
  app_id           NUMBER(6) not null,
  component_type   VARCHAR2(50) not null,
  component_key    VARCHAR2(255),
  parent_key       VARCHAR2(255),
  page_id          NUMBER(6),
  role_id          NUMBER not null,
  permission_code  VARCHAR2(30) not null,
  effective_from   DATE default TRUNC(SYSDATE) not null,
  effective_to     DATE,
  created_by       VARCHAR2(128) default COALESCE(
                                          SYS_CONTEXT('APEX$SESSION','APP_USER'),
                                          SYS_CONTEXT('USERENV','SESSION_USER')
                                      ),
  created_on       TIMESTAMP(6) default SYSTIMESTAMP,
  modified_by      VARCHAR2(128),
  modified_on      TIMESTAMP(6),
  component_key_uk as (COALESCE("COMPONENT_KEY",''||CHR(0))),
  page_id_uk       as (COALESCE(TO_CHAR("PAGE_ID"),''||CHR(0)))
);
-- Add comments to the table 
comment on table T_AUTH_COMPONENT_PERMS
  is 'Role-to-component permission mapping. Uses component keys (static_id/name) ';
-- Add comments to the columns 
comment on column T_AUTH_COMPONENT_PERMS.app_id
  is 'Application scope';
comment on column T_AUTH_COMPONENT_PERMS.component_key
  is 'page number for PAGE as string, static_id or name for other components. NULL for APPLICATION level.';
comment on column T_AUTH_COMPONENT_PERMS.parent_key
  is 'Parent component for hierarchy. If NULL, hierarchy is going to be determined by component_type';
comment on column T_AUTH_COMPONENT_PERMS.page_id
  is 'Page context for components that belong to a page (regions, items, buttons, processes).';
comment on column T_AUTH_COMPONENT_PERMS.role_id
  is 'role_id from roles table';
-- Create/Recreate indexes 
create index IDX_ACP_LOOKUP on T_AUTH_COMPONENT_PERMS (APP_ID, COMPONENT_TYPE, COMPONENT_KEY, ROLE_ID);
create index IDX_ACP_PAGE on T_AUTH_COMPONENT_PERMS (APP_ID, PAGE_ID, COMPONENT_TYPE);
create index IDX_ACP_ROLE on T_AUTH_COMPONENT_PERMS (ROLE_ID);
create unique index UK_ACP_GRANT on T_AUTH_COMPONENT_PERMS (APP_ID, COMPONENT_TYPE, COMPONENT_KEY_UK, PAGE_ID_UK, ROLE_ID);
-- Create/Recreate primary, unique and foreign key constraints 
alter table T_AUTH_COMPONENT_PERMS
  add constraint PK_AUTH_COMP_PERMS primary key (PERM_ID)
  using index;
alter table T_AUTH_COMPONENT_PERMS
  add constraint FK_ACP_ROLE foreign key (ROLE_ID)
  references t_app_roles (ROLE_ID) on delete cascade;
-- Create/Recreate check constraints 
alter table T_AUTH_COMPONENT_PERMS
  add constraint CK_ACP_APP_NULL_KEY
  check (component_type != 'APPLICATION' OR component_key IS NULL);
alter table T_AUTH_COMPONENT_PERMS
  add constraint CK_ACP_COMP_TYPE
  check (component_type IN (
            'APPLICATION','PAGE','REGION','ITEM','BUTTON','PROCESS',
            'NAV_ENTRY','NAV_BAR','LIST_ENTRY','TAB','MENU', 'APEX_APPLICATION_PAGES'
        ));
alter table T_AUTH_COMPONENT_PERMS
  add constraint CK_ACP_DATE_RANGE
  check (effective_to IS NULL OR effective_to >= effective_from);
alter table T_AUTH_COMPONENT_PERMS
  add constraint CK_ACP_PERM_CODE
  check (permission_code IN ('ADMIN','EDIT','VIEW','DENY'));
